apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app: test
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: |-
    {{ $value | nindent 4 }}
{{- end }}
  password: <path:kv-v2/data/argocd#password>
